nrc-no/core

- api2/pkg/parties/parties/client.go
- api2/pkg/parties/parties/rest.go
- api2/pkg/parties/parties/store.go
- api2/pkg/webapp/cases.go
- api2/pkg/webapp/templates/casenew.gohtml
Should work. But SSR forces page refresh on case type choice. Maybe a better solution would filter the parties client-side?
> bugfix: case view restricts parties options based on party type

- api2/pkg/individuals/store.go
- New default behaviour of List is to filter on partyTypeIds looking for individuals
- If ListOptions is passed in, the behaviour is to `and` the list options filter with the individual partyTypeIds filter
> COR-13: modify individual List to only include individuals and not all parties

- api2/pkg/parties/attributes/client.go
- api2/pkg/parties/attributes/rest.go
- api2/pkg/parties/attributes/store.go
- api2/pkg/testing/attribute_test.go
- api2/pkg/webapp/individuals.go
- api2/pkg/webapp/settings.go
- api2/pkg/webapp/templates/attribute.gohtml
- api2/pkg/webapp/templates/attributes.gohtml
- On attribute API, move from static subject type to using party type
- Use hardcoded static individual type in the subject type dropdown on the attribute definition page
- Filter the list of attributes in the backend to retrieve only those who apply to a beneficiary
> COR-15: only show relevant attributes

- api2/pkg/parties/attributes/store.go
- api2/pkg/webapp/settings.go
- api2/pkg/webapp/templates/attribute.gohtml
fixed; also renamed html 'name' attribute to isPii to conform with json/bson nomenclature defined in the attribute api
> COR-46-fix-personal-info-not-saving

- api/.run/start.run.xml
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/renderer.go
- api/pkg/apps/webapp/templates/individual.gohtml
- api/pkg/apps/webapp/templates/notifications.gohtml
- api/pkg/sessionmanager/interface.go
Basic notifications ("flashes") are now possible on any page by
1. Adding a call to `server.sessionManager.AddNotification(ctx, notification)` in the rendering file (eg. `webapp/individuals.go`)
2. Adding a reference to `{{template "notifications}}` in a page
This PR implements notifications on Individual creation/updates
> Cor 60 notifications

- api/pkg/apps/iam/types.go
As per @ludydoo 's guidance, I have altered the way the party .String function behaves
Now the IDs are replaced with a human readable string as can be seen on this case:
> COR-14: add way to represent party as a string for display purposes

- api/pkg/apps/login/credentials_post.go
- api/pkg/apps/login/passwords.go
- api/pkg/apps/login/server.go
Diagnosed problem where user could not login after setting credentials:
- Null request was being sent to Hydra from app
- Null request happened because we did not store credential in MongoDB
To remedy:
1. Added a new method called PostCredential() which takes care of hashing, salting and storing the password in MongoDB
> COR-113: User cannot login after setting credential

- api/pkg/apps/webapp/templates/head.gohtml
- api/pkg/apps/webapp/templates/individual.gohtml
The party selector list now no longer gets hidden when clicking on the focused input.
Please excuse the google autofill dropdown that gets rendered by Chrome over the dropdown in the demo:
> COR-177: add logic to prevent dropdown list getting hidden on click

- api/pkg/apps/webapp/cases.go
- caseTypeId was sometimes a blank string when being used to retrieve the caseType in order to access the template needed to submit a case, this caused a nil template and thus an error
- added a check to ensure that caseTypeId is not a blank, if it is we try to get the caseTypeId from the submitted form and if that fails we return a specific error
> COR-181: Fix bug on case submission

- api/pkg/apps/webapp/templates/dropdown.gohtml
Some leftover code wasn't removed from the dropdown template which was breaking it. Also the select tag was not closed.
Fixing this revealed a UX bug detailed in COR-193
> Cor 192 fix dropdown template

- .idea/watcherTasks.xml
- api/pkg/apps/webapp/individual_registration_controller.go
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/templates/individuals.gohtml
As a { Project Manager | Enumerator | Triage Staff | Expert }
I want to see a beneficiaries status from the beneficiary list page
So that I can take pertinent actions for this beneficiary
Technical Description:
Beneficiary entry should show status. If status is an action, status should be a button pointing to form.
Since we did not yet go down the route of using actions, the later part of the requirement:
> If status is an action, status should be a button pointing to form.
Has not been implemented.
> COR-149: add registration status label to invididual list page

- api/pkg/apps/seeder/static.go
1. Define intake casetype per team to allow inferring beneficiary status for intake
2. Teams must have an associated intake casetype
3. There should be intake casetypes for Individuals
> COR-168-COR-169-COR-171: preparing for team intake labels on beneficiary list page

- api/pkg/apps/cms/case_get.go
- api/pkg/apps/cms/types.go
- api/pkg/apps/webapp/individuals.go
This turned out to be kind of redundant after COR-187 Registration Subpages because the intake case tab buttons remain disabled until the attributes stage has been completed. Nevertheless, the webapp's behavior now further ensures the Cases passed to the renderer are marked as readonly if the attributes haven't been filled out.
> Cor 186 Prevent intake case editing until attribute are filled out

- api/pkg/apps/iam/attribute_store.go
- api/pkg/apps/iam/client_interface.go
- api/pkg/apps/iam/static.go
- api/pkg/apps/webapp/attributes.go
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/profile.go
- Added `CountryID` to `Attribute`. Each attribute is now given either `GlobalCountry.ID` or a specific country ID defined in `iam.static.go`
- Added `CountryIDs` to `AttributeListOptions`. By passing `CountryIDs: []string{iam.GlobalCountry.ID, countryID}` we get attributes that are either global or match countryID
- Added `GetCountryFromLoginUser` in `profile.go`, which returns the country ID of the team of the login user.
- Attributes in `Attribute Settings` and `Individuals` are now only showing global attributes and attributes specific to login user's country.
> COR-235: Country specific attributes

- .gitignore
- e2e/cypress/integration/attribute.spec.js
- e2e/cypress/integration/case.spec.js
- e2e/cypress/integration/casetype.spec.js
- e2e/cypress/integration/individual.spec.js
- e2e/cypress/integration/pagination.spec.js
- e2e/cypress/integration/partytype.spec.js
- e2e/cypress/integration/relationshiptype.spec.js
- e2e/cypress/integration/team.spec.js
- e2e/cypress/support/index.js
This aims to refactor end-to-end tests to allow for different login behaviour on a per test basis, replacing the global `beforeEach` login approach.
The rationale behind this is that certain tests will depend on a specific type of user being logged in, and we therefore need more granular control than a global catch all can provide.
> COR-243: Refactor e2e tests

- cmd/devinit/main.go
The `creds` directory was not created by default, was making the init steps fail
> Create creds directory on dev init

- web/pwa/package.json
- web/pwa/yarn.lock
axa-fr/react-oidc-context was used in a previous iteration
> Remove unused depency in PWA

- .prow/push-core-go-test.yaml
- pkg/api/meta/utils.go
- pkg/api/types/folder.go
- pkg/api/types/scheme.go
- pkg/server/public/handlers/folder/create.go
- pkg/store/constants.go
- pkg/store/database.go
- pkg/store/database_test.go
- pkg/store/errors.go
- pkg/store/factory.go
- pkg/store/folder.go
- pkg/store/folder_test.go
- pkg/store/identity_provider.go
- pkg/store/main_test.go
**Changes to the `store.Suite`**
There was already logic to setup a `store.DatabaseSuite` test suite. I've renamed this to just `store.Suite`. This `store.Suite` is the parent `Suite` for all store tests. 
So there is now `store.Suite` (instead of `store.DatabaseSuite`), and methods like
- `func (s *Suite) TestDatabaseCreate() {}`
- `func (s *Suite) TestFolderCreate() {}` 
- ...
**Changes in this PR**
- Removed unecessary `db.WithContext(ctx)`as this logic is already in the `store.actionContext`, which is the boilerplate code for all store actions.
- Added checks when creating a `Folder` for the existence of the `Database` and `parent` folder (if any), as well as the appropriate error messages
- Fixed error where a foreign key constraint would fail, even if we specify an empty string for …
> Tests and documentation for the Folder store

- frontend/.gitignore
- frontend/apps/admin/package.json
- frontend/apps/native/package.json
- frontend/apps/pwa/package.json
- frontend/lerna.json
- frontend/package.json
- frontend/packages/core-api-client/package.json
- frontend/packages/core-auth/package.json
- frontend/packages/design-system/package.json
- frontend/storybook/package.json
Adds a new directory as a lerna root package, containing apps and packages. I've renamed some for clarity.
`web/admin` -> `frontend/apps/admin`
`web/app/frontend` -> `frontend/apps/native`
`web/pwa` -> `frontend/apps/pwa`
`web/auth` -> `frontend/packages/core-auth`
`web/app/client` -> `frontend/packages/core-api-client`
`web/designSystem` -> `frontend/packages/design-system`
`web/storyBook` -> `frontend/storybook`
> Core 381 frontend monorepo skeleton

- pkg/api/types/record.go
- pkg/api/types/validation/record.go
- pkg/api/types/validation/record_test.go
- pkg/server/public/handlers/record/create.go
- pkg/sqlmanager/build_helpers.go
- pkg/sqlmanager/build_subform_field.go
- pkg/sqlmanager/constants.go
- pkg/sqlmanager/formreader.go
- pkg/sqlmanager/formreader_test.go
- pkg/sqlmanager/formwriter.go
- pkg/sqlmanager/formwriter_test.go
- pkg/store/record.go
- pkg/testutils/options.go
- pkg/utils/pointers/pointers.go
- web/app/client/src/lib/types/index.ts
- web/app/frontend/yarn.lock
- web/pwa/src/components/RecordPicker.tsx
- web/pwa/src/features/browser/FolderBrowser.tsx
- web/pwa/src/features/browser/FormBrowser.tsx
- web/pwa/src/features/browser/RecordBrowser.tsx
- web/pwa/src/features/former/former.slice.ts
- web/pwa/src/features/recorder/FieldEditor.tsx
- web/pwa/src/features/recorder/RecordEditor.tsx
- web/pwa/src/features/recorder/recorder.slice.ts
Modifying the record.Values to be a []FieldValue instead of a map[string]interface{}. Much easier to deal with..
Also, all values passed to the API for field values are string or null
This also introduces a `formwriter` and `formreader` to read/write records
```
POST /records
{ 
"formId":"...",
"databaseId":"...",
"values": [
{"fieldId":"field-1","value":"123"}
]
}
```
> Change Record Values from map to slice

- pkg/server/auth/server.go
The `authnz-bouncer` is ran as a `ext_authz` plugin on envoy. It's a catch-all requests, so we need to listen to all requests.
The current path prefix was only listening to /apis/authorization.nrc.no/v1...
> COR-414 fix authnz-bouncer path prefix

- cmd/dev.go
- cmd/devinit/main.go
The previous logic was prompting for a `pet-name` on startup, even when running `core serve all`, etc. That broke running the server on the cloud, since it does not make sense to provide a pet name on kubernetes. It's only for local development
> COR-408 do not run devinit on startup

- build/package/core.Dockerfile
- configs/authnz-frontend/replace-env-vars.sh
- configs/core-frontend/replace-env-vars.sh
Didn't find a way to use scratch as a base image yet. Seems that linking sqlite causes quite a lot of problems on that front. Reverting to golang base image for now
Also, use env substitution for css files
> COR-424 fix docker build

- pkg/server/formsapi/tests/record_test.go
- pkg/sqlmanager/build_single_select_field.go
- pkg/sqlmanager/schema_test.go
Forgot the case where `singleSelect` fields might have a null value. It did work anyways, because postgres's handling of NULL values and checks. But simply making it explicit in the `CHECK` constraint that we can receive a null value.
> Handle checks for null/not null single select cases

- Makefile
- scripts/serve-backend.sh
This pr adds a make command to run everything needed for the backend. It's intend to be used when developing the frontend.
On startup it:
* Start tunnels
* Start local proxy
* Start up docker containers
* Run bootstrap
* Start api server
On exit it:
* Kills all running processes
* Tears down docker containers
Some nice additional features for the future:
* Options to disable various bits (eg. don't run the server because you want to run it with a debugger)
* Option to configure the docker timeout (30s may be too long)
> Serve backend command

- frontend/packages/core-api-client/src/lib/types/index.ts
- pkg/api/types/defaults/form.go
- pkg/api/types/form.go
- pkg/api/types/validation/form.go
- pkg/api/types/validation/form_test.go
- pkg/server/formsapi/handlers/form/create.go
- pkg/server/formsapi/tests/form_test.go
- pkg/store/form.go
- pkg/store/form_test.go
This PR adds the "Type" field to the FormDefinition, as well as add logic to store this new field, and validate the value on the `POST /formdefinitions`
> COR-499 add form type

- pkg/api/types/scheme.go
- pkg/api/types/validation/form.go
- pkg/api/types/validation/recipient.go
- pkg/api/types/validation/recipient_test.go
- pkg/server/formsapi/handlers/form/create.go
- pkg/server/formsapi/handlers/form/create_test.go
Added validation for "Recipient" forms
The validation happens in two parts
1. The static validation, things we can infer without having to make any database calls. That lies in the default "validation" package, where all other validation currently lies.
2. The dynamic validation, that happens for now in the POST /formdefinitions handler. Here, we must make a DB call to check if the "parent" of a recipient form is also a recipient form.
This PR is based off COR-499 branch, so I set the PR target to the COR-499 branch until the other one gets merged into main
> COR-450 add validation for recipient forms
