nrc-no/core

- libs/formbuilder/src/lib/components/fieldbuilder/fieldbuilder.component.tsx
- libs/formbuilder/src/lib/components/fieldconfig/fieldconfig.component.tsx
- libs/formbuilder/src/lib/components/fieldinfo/fieldinfo.component.tsx
- libs/formbuilder/src/lib/components/fieldtype/fieldtype.component.tsx
- libs/shared/ui-toolkit/src/lib/components/accordion/accordion.component.tsx
- libs/shared/ui-toolkit/src/lib/components/accordion/accordion.stories.tsx
- libs/shared/ui-toolkit/src/lib/components/button/button.component.tsx
- libs/shared/ui-toolkit/src/lib/components/button/button.stories.tsx
- libs/shared/ui-toolkit/src/lib/components/card/card.component.tsx
- libs/shared/ui-toolkit/src/lib/components/collapse/collapse.component.tsx
- libs/shared/ui-toolkit/src/lib/components/container/container.component.tsx
- libs/shared/ui-toolkit/src/lib/components/form-input/form-input.component.tsx
- libs/shared/ui-toolkit/src/lib/components/form-input/form-input.spec.tsx
- libs/shared/ui-toolkit/src/lib/components/form-label/label.component.tsx
- libs/shared/ui-toolkit/src/lib/components/form-select/form-select.component.tsx
- libs/shared/ui-toolkit/src/lib/components/icons/icons.tsx
- libs/shared/ui-toolkit/src/lib/components/list-group/list-group.component.tsx
- libs/shared/ui-toolkit/src/lib/components/modal/modal.stories.tsx
- libs/shared/ui-toolkit/src/lib/components/modal/modal.tsx
- libs/shared/ui-toolkit/src/lib/components/progress-bar/progress-bar.component.tsx
- libs/shared/ui-toolkit/src/lib/components/select/select.component.tsx
- libs/shared/ui-toolkit/src/lib/components/tab/tabs.component.tsx
- libs/shared/ui-toolkit/src/lib/components/tab/tabs.stories.tsx
- libs/shared/ui-toolkit/src/lib/utils/ReactUtilityTypes.d.ts
> Import and props changes + tab and accordion prototypes

- api2/go.mod
- api2/pkg/parties/api/types.go
- api2/pkg/webapp/relationshiptypes.go
- api2/pkg/webapp/templates/relationshiptype.gohtml
- api2/pkg/webapp/templates/relationshiptypes.gohtml
[Notion Ticket](https://www.notion.so/nrcdteam/4b47929ef6f047b0bf9c0409ae2138d4?v=31682fcf226d4f57a2e78aee2e0c78ce&p=fe22598767004f33bf826818aaa5b416)
Purpose:
Add party type rules UI allowing user to select the types of parties that can be used for a specific relationship
> Relationship rules

- api2/pkg/parties/api/types.go
- api2/pkg/parties/relationshiptypes/client.go
- api2/pkg/parties/relationshiptypes/rest.go
- api2/pkg/parties/relationshiptypes/store.go
- api2/pkg/webapp/templates/relationshiptype.gohtml
- updates work now
- switched from JS form submission to default
> Fixing issues with editing 

- api2/pkg/parties/relationshiptypes/api.go
- api2/pkg/parties/relationshiptypes/rest.go
- api2/pkg/parties/relationshiptypes/static.go
- api2/pkg/parties/relationshiptypes/store.go
- api2/pkg/webapp/relationshiptypes.go
- api2/pkg/webapp/templates/relationshiptype.gohtml
- api2/pkg/webapp/templates/relationshiptypes.gohtml
- Introduced a new field on the relationship type entity `isDirectional`
- Modified Go code to handle this new field (client, store, api etc...)
- Added JavaScript to make UI conditional on the isDirectional
> Update relationship type definition to handle directional relationships

- api2/pkg/parties/relationshiptypes/api.go
- api2/pkg/parties/relationshiptypes/client.go
- api2/pkg/parties/relationshiptypes/rest.go
- api2/pkg/parties/relationshiptypes/store.go
- api2/pkg/webapp/beneficiaries.go
- api2/pkg/webapp/relationshiptypes.go
- add Reversed method to RelationshipType struct, which switches first and second parties
- add filter to List endpoint for RelationshipTypes
- beneficiary relationship dropdown gets filtered list of relationship types
> Beneficiary relationship dropdown

- api2/artifacts/realm.json
- api2/pkg/auth/handler.go
- api2/pkg/auth/helpers.go
- api2/pkg/auth/middleware.go
- api2/pkg/webapp/cases.go
- api2/pkg/webapp/casessettings.go
- api2/pkg/webapp/casetypes.go
- api2/pkg/webapp/countrysettings.go
- api2/pkg/webapp/handler.go
- api2/pkg/webapp/individuals.go
- api2/pkg/webapp/partytypes.go
- api2/pkg/webapp/relationshiptypes.go
- api2/pkg/webapp/renderer.go
- api2/pkg/webapp/settings.go
- api2/pkg/webapp/teams.go
- api2/pkg/webapp/templates/cases.gohtml
- api2/pkg/webapp/templates/nav.gohtml
(the code about auth is part of #27 , forgot to branch from main instead of that one)
Also introduced a method "IsLoggedIn" that can be used in templates to display Sign In or Sign Out button
> COR-35 Add template renderer to share common methods between templates

- api2/pkg/cases/casetypes/api.go
- api2/pkg/cases/casetypes/rest.go
- api2/pkg/cases/casetypes/static.go
- api2/pkg/cases/casetypes/store.go
- api2/pkg/webapp/casetypes.go
- api2/pkg/webapp/templates/casetype.gohtml
1. Add team ID to case type struct
2. On case type creation show dropdown for team
> COR-22: select casetype team

- api2/pkg/memberships/static.go
- api2/pkg/parties/relationshiptypes/api.go
- api2/pkg/parties/relationshiptypes/static.go
- api2/pkg/parties/relationshiptypes/store.go
- api2/pkg/staff/static.go
- api2/pkg/teamorganizations/static.go
- api2/pkg/testing/relationship_type_test.go
- api2/pkg/webapp/casetypes.go
- api2/pkg/webapp/individuals.go
- api2/pkg/webapp/relationshiptypes.go
- api2/pkg/webapp/templates/individual.gohtml
- api2/pkg/webapp/templates/relationshiptype.gohtml
- api2/pkg/webapp/templates/relationshiptypes.gohtml
- Renamed party type fields to party type ids
- Had to make some small changes to Case code to get the tests to run, but the case tests still have 2 failing cases @ludydoo 
- Checked the features in the UI and it seems to work, despite the failing Case tests
> COR-41: Refactor relationship type rules

- api2/pkg/webapp/templates/cases.gohtml
> COR-43-swapped-case-status-symbols

- api2/pkg/cases/cases/api.go
- api2/pkg/cases/cases/rest.go
- api2/pkg/cases/cases/static.go
- api2/pkg/cases/cases/store.go
- api2/pkg/webapp/cases.go
- api2/pkg/webapp/templates/case.gohtml
- api2/pkg/webapp/templates/casenew.gohtml
Show case teams on new case and case page
> COR-23: Show case teams on new case and case page

- api2/pkg/webapp/partytypes.go
- api2/pkg/webapp/templates/partytype.gohtml
Template wasn't getting enough info (only ID) and wasn't doing conditional rendering.
Also changed the flow to redirect the user to the PartyType list after saving a change.
> Cor 48 fix partytype view nodata

- api2/pkg/parties/partytypes/api.go
- api2/pkg/teams/api.go
- api2/pkg/webapp/casetypes.go
- api2/pkg/webapp/templates/casetype.gohtml
- api2/pkg/webapp/templates/casetypes.gohtml
fixed
also improved the casetype list view to match the rest of the UI more closely
> Cor 50 fix casetype team not saved

- api2/pkg/parties/partytypes/api.go
- api2/pkg/webapp/templates/attributes.gohtml
fix PartyType subject not being displayed; add comma separator for mulltiple values
> COR-47-fix attribute subject in list view

- api/pkg/apps/iam/client_interface.go
- api/pkg/apps/iam/party_client.go
- api/pkg/apps/iam/party_search.go
- api/pkg/apps/iam/party_store.go
- api/pkg/apps/iam/server.go
- api/pkg/apps/iam/team_store.go
- api/pkg/apps/iam/types.go
- api/pkg/apps/webapp/cases.go
- api/pkg/apps/webapp/templates/case.gohtml
Added parties `search` endpoint (useful when searching parties with a payload that exceeds max URL length)
Slightly refactored Case view
Added usernames on case comments
> COR-95 Display comment authors on case view

- api/pkg/apps/cms/types.go
- api/pkg/apps/webapp/cases.go
- api/pkg/apps/webapp/templates/case.gohtml
Records the referring user's first and last names for the moment. Ideally would record a unique identifier.
> COR-24 Show referral creator

- api/pkg/apps/cms/types.go
- api/pkg/apps/webapp/templates/casetype.gohtml
> COR-134 improve template rendering in casetype view

- docs/README.md
- docs/_config.yml
issue not done, just need to test ghpages
> initialize ghpages

- .gitignore
- api/pkg/apps/iam/init.go
- api/pkg/apps/iam/static.go
- api/pkg/apps/seeder/static.go
- api/pkg/apps/webapp/templates/head.gohtml
- Hardcode actual teams and users that will be using the app
- Add party attributes
- Add case templates
> COR-112: Uganda demo preparation

- api/pkg/apps/webapp/constants.go
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/server.go
- api/pkg/apps/webapp/teams.go
- api/pkg/apps/webapp/templates/individual.gohtml
- api/pkg/apps/webapp/templates/team.gohtml
Add javascript code to only render first n elements of party dropdowns
> COR-127: Limit party dropdown options

- api/pkg/apps/seeder/static.go
- artifacts/docker-compose.yaml
- Add situational analysis case for Bo Diddley with form data
- Made slight modification to docker-compose, without which it wont run on my machine (Ubuntu 18.04 LTS)
> COR-143: Add static case with form data, allowing it to render without errors.

- api/pkg/apps/iam/client_interface.go
- api/pkg/apps/iam/individual_store.go
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/templates/individuals.gohtml
- Added search param attribute to individual list options
- Added a text based search to individual store, if the search param attribute is set
- Added some JS to the individuals template to redirect with query params
> COR-135: Fix individual search

- api/pkg/apps/webapp/individuals.go
tiny bug preventing server spinup on main
> COR-162 quickfix unknown variable

- api/pkg/sessionmanager/interface.go
> COR-163 fix notification flashes

- api/pkg/apps/webapp/templates/individual.gohtml
> Cor 176 relationship display bug

- api/pkg/apps/webapp/templates/individual.gohtml
> COR-178 fixed duplicate and invalid relationships

- .idea/core.iml
- .idea/jsLibraryMappings.xml
- .idea/watcherTasks.xml
- api/pkg/apps/cms/case_post.go
- api/pkg/apps/cms/case_put.go
- api/pkg/apps/cms/case_validation.go
- api/pkg/apps/cms/types.go
- api/pkg/apps/seeder/static.go
- api/pkg/apps/webapp/caseform.go
- api/pkg/apps/webapp/cases.go
- api/pkg/apps/webapp/individual_registration_controller.go
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/registration_controller.go
- api/pkg/apps/webapp/registration_handler.go
- api/pkg/apps/webapp/server.go
- api/pkg/apps/webapp/templates/casetype.gohtml
- api/pkg/apps/webapp/templates/checkbox.gohtml
- api/pkg/apps/webapp/templates/dropdown.gohtml
- api/pkg/apps/webapp/templates/formfield.gohtml
- api/pkg/apps/webapp/templates/individual.gohtml
- api/pkg/apps/webapp/templates/individuals.gohtml
- api/pkg/apps/webapp/templates/taxonomyinput.gohtml
- api/pkg/apps/webapp/templates/taxonomyinput_script.gohtml
- api/pkg/apps/webapp/templates/team.gohtml
- api/pkg/apps/webapp/templates/textarea.gohtml
- api/pkg/apps/webapp/templates/textinput.gohtml
- api/pkg/apps/webapp/templates/validation_feedback.gohtml
- api/pkg/registrationctrl/registrationctrl.go
- api/pkg/registrationctrl/registrationflow.go
- api/pkg/validation/errors.go
This PR is a bulk one for final preparations before we begin UAT in Uganda.
It mainly intends to move a subset of cases, namely those involved in the intake process, into the individual registration flow.
This is achieved by using work completed previously including the Registration Controller. The UI of the individual view is modified to include the cases beneath the Attributes.
It also fixes some issues:
- re-adding taxonomyinput case element type
This PR was worked on in collaboration with @nilueps
> COR-167: UI Modifications for UAT in UG

- api/pkg/apps/webapp/templates/individual.gohtml
Added tabbed layout via bootstrap. Purely cosmetic, the underlying functionality should be unaffected
> COR-187 Individual sub-pages

- api/pkg/apps/iam/static.go
- api/pkg/apps/seeder/static.go
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/templates/individual.gohtml
- api/pkg/apps/webapp/templates/individuals.gohtml
- Added `beneficiary` PartyType
- Display only beneficiaries in individuals page
> COR-184: Segregating individual-staff and individual-beneficiary

- .gitignore
- api/pkg/apps/webapp/auth.go
- api/pkg/apps/webapp/auth_login.go
- e2e/cypress/integration/team.spec.js
Bjorn has suggested some changes to the secure-cookie bug fix we shipped earlier. This ticket implements the changes requested.
I also added a fix for a failing team page UI test that was caused by recent changes to the seeder:
- Courtney Lare is already a member of the team being tested, so the UI test was failing on an assertion looking for them in the parties dropdown
- I replaced Courtney Lare with myself as the test subject
> COR-211: Code quality improvements suggested by Bjorn

- .idea/runConfigurations/e2e__browser_.xml
- api/pkg/apps/webapp/individuals.go
- api/pkg/apps/webapp/templates/fe_taxonomyinput.gohtml
- api/pkg/apps/webapp/templates/individual.gohtml
- api/pkg/apps/webapp/templates/individuals.gohtml
- api/pkg/validation/validation.go
- e2e/cypress.json
- e2e/cypress/helpers/index.js
- e2e/cypress/integration/individual.spec.js
- e2e/cypress/pages/individualOverview.page.js
- e2e/cypress/pages/individualPage.js
- e2e/package-lock.json
- e2e/package.json
1. Navigate to the New Individual page from the individuals list page
2. Fill out minimal registration attributes (first & last names, birthdate, email, status, gender)
3. Add relationship
4. Save
4. Search for newly created Individual
5. Verify values
5. Update attributes with new values, including new relationship. Save.
6. Search again. Verify updated values.
7. Fill out Situation Analysis. Save. Verify.
8. Fill out Response. Save. Verify.
> Cor 202 update individual e2e test

- api/pkg/apps/iam/init.go
- api/pkg/apps/iam/static.go
- api/pkg/apps/iam/types.go
- api/pkg/apps/seeder/static.go
Added following individual intake attributes:
- Date of Identification (Date)
- Location of Identification (dropdown)
- Source of Identification (dropdown)
- District / Admin 2 (dropdown)
- Subcounty / Admin 3 (text)
- Parish / Admin 4 (text)
- Village / Admin 5 (text)
> COR-224: Added new intake attributes

- .gitignore
- api/pkg/apps/seeder/static.go
- api/pkg/apps/webapp/templates/fe_taxonomyinput.gohtml
- api/pkg/apps/webapp/templates/fe_taxonomyinput_script.gohtml
- e2e/cypress/integration/individual.spec.js
- e2e/cypress/pages/individualPage.js
This ticket comes from feedback from our stakeholder in Uganda, Stephen:
- The taxonomy inputs have been adjusted to only have one level of the taxonomy.
- Additional textarea fields have been added to allow for user comment on the taxonomy inputs
- Individual e2e test has been adjusted to account for new fields
> COR-226: Update Response Form for UG

- docs/ARCHITECTURE.md
- docs/CONTRIBUTING.md
> Cor 236 dev docs

- api/pkg/apps/iam/init.go
- api/pkg/apps/iam/static.go
- Tertiary phone number
- Instructions on contacting the beneficiary (textarea)
- Can NRC initiate contact? (chkbx)
> COR-225: Uganda contact attributes

- .gitignore
- docs/GLOSSARY.md
- docs/README.md
Adds a glossary doc with commonly used terms and their meanings, can be maintained going forward as a source of truth on terminology.
> COR-219: Add glossary

- api/pkg/apps/seeder/static.go
- api/pkg/apps/webapp/templates/fc_hint.gohtml
- api/pkg/apps/webapp/templates/form_control.gohtml
- api/pkg/form/control.go
- api/pkg/form/validation.go
this doesn't fulfill the ticket requirements because of time constraints.
It doesn't add the ability to show hint dynamically, it only adds a `Hint` form control type with static text content.
> COR 262 form hints

- api/pkg/apps/seeder/static.go
- add new case type ICLA Case Closure
- harmonise case type names
> COR-266: New Case Type (Kampala ICLA Case Closure)

- api/pkg/apps/seeder/static_case_types.go
Remove “other services requested” in the UG response form as well as comments
> COR-281: Remove other services and comments

- .gitignore
- api/pkg/apps/webapp/cases.go
- api/pkg/apps/webapp/static/validation.js
- api/pkg/apps/webapp/static/validation.ts
- api/pkg/server/options.go
server-side validation wasn't being properly applied, should be working now.
> fix validation.js

- api/pkg/apps/cms/case_put.go
- api/pkg/apps/webapp/templates/case.gohtml
- api/pkg/apps/webapp/templates/individual.gohtml
- e2e/cypress/integration/case.spec.js
- e2e/cypress/integration/individual.spec.js
- e2e/cypress/pages/individualPage.js
- renable case re-opening after UG feedback
- formatting fix
- update tests and add done checks
> COR 282 enable reopening cases

- web/app/client/package.json
- web/app/client/yarn.lock
- web/auth/yarn.lock
> typescript dev dependency for web/app/client

- go.mod
- go.sum
- pkg/api/types/database.go
- pkg/server/public/handlers/database/create.go
- pkg/store/clear.go
- pkg/store/clear_test.go
- pkg/store/context.go
- pkg/store/database.go
- pkg/store/database_test.go
- pkg/store/errors.go
Added documentation for the database store
Added tests for the database store, and found a bug or two
> database store tests and documentation

- web/app/frontend/__tests__/screens/FormsScreen.test.js
- web/app/frontend/__tests__/screens/FormsScreen.test.tsx
- web/app/frontend/__tests__/screens/__snapshots__/FormsScreen.test.tsx.snap
- web/app/frontend/jest.setup.js
- web/app/frontend/package.json
- web/app/frontend/src/components/Router.tsx
- web/app/frontend/src/components/screen_containers/FormsScreenContainer.tsx
- web/app/frontend/src/components/screens/FormsScreen.tsx
- web/app/frontend/src/constants/testIds.js
- web/app/frontend/src/reducers/recordsReducers.ts
- web/app/frontend/src/types/screens.ts
- web/app/frontend/yarn.lock
test with: `yarn test __tests__/screens/FormsScreen.test.js`
> COR 340 PARTIAL FormsScreen Test

- frontend/apps/native/__tests__/screens/ViewRecordScreen.test.tsx
- frontend/apps/native/__tests__/screens/__snapshots__/ViewRecordScreen.test.tsx.snap
- frontend/apps/native/src/components/screens/ViewRecordScreen.tsx
- separate screen and container
- add tests
> COR 340 PARTIAL ViewRecordScreen test

- frontend/apps/native/__tests__/screen_containers/ViewRecordScreenContainer.test.tsx
- frontend/apps/native/__tests__/screen_containers/__snapshots__/ViewRecordScreenContainer.test.tsx.snap
- frontend/apps/native/src/components/Router.tsx
- separate screen and container
- rename
- container
- add tests
> COR 340 PARTIAL ViewRecordScreenContainer test

- frontend/apps/native/__tests__/screen_containers/RecordsScreenContainer.test.tsx
- frontend/apps/native/__tests__/screen_containers/__snapshots__/RecordsScreenContainer.test.tsx.snap
- web/app/frontend/src/components/screens/RecordsScreen.tsx
- separate screen and container
- add tests
> COR 340 PARTIAL RecordsScreenContainer test

- cmd/devinit/core.go
- pkg/server/login/handlers/login/action.go
- pkg/server/login/handlers/login/handler.go
- pkg/server/login/server.go
- pkg/server/options/options.go
The urls.self was ignored (overwritten) anyways
> COR-415 remove urls.self server option

- frontend/apps/admin/src/App.tsx
- frontend/apps/admin/src/app/client.ts
- frontend/apps/admin/src/client/client.ts
- frontend/apps/admin/src/hooks/hooks.tsx
- frontend/apps/pwa/src/App.tsx
- frontend/apps/pwa/src/app/client.ts
- frontend/apps/pwa/src/app/hooks.ts
- frontend/packages/core-api-client/src/lib/client.ts
- frontend/packages/core-auth/src/components/AuthWrapper.tsx
- frontend/packages/core-auth/src/types/types.ts
We need to be able to inject either the `id_token` or the `access_token`. 
This PR introduces an option to inject either
> COR-409 fix auth token injection logic

- pkg/sql/schema/sql_column_constraint.go
- pkg/sqlmanager/build_single_select_field.go
- pkg/sqlmanager/schema_test.go
Moving from creating a distinct table for each single select field to having a CHECK constraint on the column itself
> Change single select store implementation

- cmd/seed_colombia.go
- pkg/seeder/colombia_dropdown_options.go
- pkg/seeder/seed.go
- pkg/seeder/seed_colombia.go
> COR 445 Colombia Seeder  Data

- cmd/seed.go
- cmd/seed_colombia.go
- cmd/seed_global.go
- pkg/api/types/folder.go
- pkg/api/types/form_reference.go
- pkg/api/types/validation/form.go
- pkg/api/types/validation/form_test.go
- pkg/seeder/colombia_dropdown_options.go
- pkg/seeder/common_field_definitions.go
- pkg/seeder/global_dropdown_options.go
- pkg/seeder/seed.go
- pkg/seeder/seed_colombia.go
- pkg/seeder/seed_global.go
- pkg/server/authnzbouncer/authorizers/hydra.go
- pkg/server/formsapi/tests/record_test.go
- pkg/sqlmanager/build_date_field.go
- pkg/sqlmanager/build_multiline_field.go
- pkg/sqlmanager/build_quantity_field.go
- pkg/utils/dates/isoweek.go
* setup skeleton
* Delete seed_uganda.go
* add common field defs
* add build fns
* rebase; refactor; rename
* update regex
* run gofmt
* remove obsolete UgandaContext reference
* COR 445 Colombia Seeder  Data (#348)
* colombia forms
* cli cmd
* gofmt
* Update colombia_dropdown_options.go
* Update seed_colombia.go
> COR-445 Columbia Seeder

- cmd/seed_global.go
- pkg/api/types/validation/form.go
- pkg/api/types/validation/form_test.go
- pkg/seeder/colombia_dropdown_options.go
- pkg/seeder/seed.go
- pkg/seeder/seed_colombia.go
- pkg/seeder/seed_global.go
- pkg/seeder/seed_uganda.go~
- tools/main.go
Our PR wasn't exhaustive enough and an error slipped through.
> COR-445-Colombia Seeder: fix seeding error

- frontend/apps/core-app/App.tsx
- frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.test.ts
- frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
- frontend/apps/core-authnz-frontend/src/App.tsx
- frontend/apps/native/App.tsx
- frontend/apps/pwa/src/App.tsx
- frontend/apps/pwa/src/app/hooks.ts
- frontend/packages/core-api-client/src/lib/BaseRESTClient.ts
- frontend/packages/core-auth/src/components/AuthWrapper.tsx
- frontend/packages/core-auth/src/hooks/useDiscovery.ts
- frontend/packages/core-auth/src/types/request.ts
- frontend/packages/core-auth/src/types/response.ts
- frontend/packages/core-auth/src/types/types.ts
- scripts/serve-backend.sh
This probably isn't the most elegant solution, but I left the browser window open for over 30 minutes and I wasn't automatically logged out as was the case previously.
Edit: the refresh gets triggered, but I'm still getting an unauthorized response
> COR-425-Fix_token_renewal

- frontend/apps/pwa/src/components/FieldEditor/FieldEditor.tsx
- frontend/apps/pwa/src/components/formFields/BooleanFieldEditor.tsx
- frontend/apps/pwa/src/features/former/Field.tsx
- frontend/apps/pwa/src/features/former/FieldTypePicker.tsx
- frontend/apps/pwa/src/reducers/former.ts
- frontend/packages/core-api-client/src/lib/types/index.ts
- frontend/packages/core-api-client/src/lib/utils/getFieldKind.ts
- frontend/yarn.lock
- pkg/api/types/field_type.go
- pkg/api/types/field_type_test.go
- pkg/api/types/fieldkind_string.go
- pkg/api/types/validation/form.go
- pkg/api/types/validation/form_test.go
- pkg/api/types/validation/record.go
- pkg/api/types/validation/record_test.go
- pkg/seeder/common_field_definitions.go
- pkg/seeder/global_dropdown_options.go
- pkg/sqlmanager/build_boolean_field.go
- pkg/sqlmanager/build_field.go
- pkg/sqlmanager/reader.go
- pkg/sqlmanager/reader_test.go
- pkg/sqlmanager/writer.go
- pkg/sqlmanager/writer_test.go
- pkg/store/form.go
- pkg/store/form_test.go
- pkg/testutils/options.go
I've left the record rendering as the string "true" or "false". There should be a better visual indicator of this, but I think this is fine for the purposes of the pwa.
> Cor 442 add yes no field type

- Makefile
- cmd/seed.go
- pkg/seeder/common_field_definitions.go
- pkg/seeder/seed_colombia.go
- pkg/seeder/seed_global.go
- scripts/seed.sh
Modified the current seeder to create some recipient forms.
Found out that the seeder is a bit of a mess, the forms are not properly linked together for the Colombia forms.
But this is out of scope of this issue.
> COR-451 Recipient seed

- frontend/apps/native/__tests__/screen_containers/RecordsScreenContainer.test.tsx
- frontend/apps/native/__tests__/screen_containers/ViewRecordScreenContainer.test.tsx
- frontend/apps/native/__tests__/screens/ViewRecordScreen.test.tsx
- frontend/apps/pwa/src/components/FormPicker.tsx
- frontend/apps/pwa/src/features/former/FieldSections.tsx
- frontend/apps/pwa/src/features/former/FormTypeControl/FormTypeControl.component.tsx
- frontend/apps/pwa/src/features/former/FormTypeControl/FormTypeControl.container.tsx
- frontend/apps/pwa/src/features/former/FormTypeControl/index.ts
- frontend/apps/pwa/src/features/former/Former.tsx
- frontend/apps/pwa/src/features/former/FormerContainer.tsx
- frontend/apps/pwa/src/features/former/FormerField.tsx
- frontend/apps/pwa/src/features/former/types.ts
- frontend/apps/pwa/src/reducers/Former/former.reducers.ts
- frontend/apps/pwa/src/reducers/Former/former.selectors.ts
- frontend/apps/pwa/src/reducers/Former/types.ts
- frontend/apps/pwa/src/reducers/__tests__/recorder.spec.ts
- frontend/packages/core-api-client/src/lib/types/index.ts
* Adds form type dropdown when creating forms
* Does not do client side validation on recipient forms yet
* When changing to recipient form, the reference field is added automatically
* Fixed some imports in ` frontend/apps/native/__tests__`
> Cor 452 recipients pwa UI

- frontend/apps/pwa/src/components/FieldEditor/FieldEditor.tsx
- frontend/apps/pwa/src/components/formFields/CheckboxFieldEditor.tsx
- frontend/apps/pwa/src/features/former/Field.tsx
- frontend/apps/pwa/src/features/former/FieldTypePicker.tsx
- frontend/apps/pwa/src/reducers/former.ts
- frontend/packages/core-api-client/src/lib/types/index.ts
- frontend/packages/core-api-client/src/lib/utils/getFieldKind.ts
- frontend/yarn.lock
- pkg/api/types/field_type.go
- pkg/api/types/field_type_test.go
- pkg/api/types/fieldkind_string.go
- pkg/api/types/validation/form.go
- pkg/api/types/validation/form_test.go
- pkg/api/types/validation/record.go
- pkg/api/types/validation/record_test.go
- pkg/seeder/common_field_definitions.go
- pkg/sql/schema/sql_data_types_test.go
- pkg/sqlmanager/build_boolean_field.go
- pkg/sqlmanager/build_field.go
- pkg/sqlmanager/reader.go
- pkg/sqlmanager/reader_test.go
- pkg/sqlmanager/writer.go
- pkg/sqlmanager/writer_test.go
- pkg/store/form.go
- pkg/store/form_test.go
- pkg/testutils/options.go
Just a renaming of things.
Some of the sql logic still uses "boolean" as it refers to writing boolean values and would be shared across any field that writes boolean values.
> Cor 463 rename field type boolean to field type check box

- frontend/apps/pwa/src/features/former/FormerContainer.tsx
- frontend/apps/pwa/src/features/former/FormerField.tsx
- frontend/apps/pwa/src/features/former/__tests__/validation.spec.ts
- frontend/apps/pwa/src/features/former/validation.ts
added tests for the custom validation functions
> COR-471: add tests for custom validation

- frontend/.eslintrc.js
- frontend/package.json
- frontend/packages/core-api-client/src/lib/client/BaseRESTClient.ts
- frontend/packages/core-api-client/src/lib/types/client/utils.ts
- frontend/packages/core-api-client/src/lib/utils/responses.ts
Add get, post, put, delete methods to the base rest client
> Base client rest methods

- frontend/apps/pwa/src/features/former/Former.tsx
- frontend/apps/pwa/src/features/former/__tests__/validation.spec.ts
- frontend/apps/pwa/src/features/former/validation.ts
[COR-466]
validate recipient forms on submit
[COR-466]: https://dteam-nrc.atlassian.net/browse/COR-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> COR-466: recipient form validation

- frontend/apps/core-app/src/screens/LoginScreen/__snapshots__/LoginScreen.component.test.tsx.snap
- frontend/packages/design-system/src/themes/Button.ts
- frontend/packages/design-system/src/themes/FormControlErrorMessage.ts
- frontend/packages/design-system/src/themes/FormControlHelperText.ts
- frontend/packages/design-system/src/themes/FormControlLabel.ts
- frontend/packages/design-system/src/themes/Input.ts
- frontend/packages/design-system/src/themes/Text.ts
- frontend/packages/design-system/src/themes/index.ts
- frontend/packages/design-system/src/tokens/typography.ts
- frontend/storybook/storybook/stories/Input/Input.stories.js
- frontend/storybook/storybook/stories/Text/Text.stories.js
[COR-470] / [COR-480]
while writing the theme for the text areas, I noticed several missing text styles
* added the missing text styles
* adjusted text story in storybook
* used correct styles in input & formcontrols and buttons
[COR-470]: https://dteam-nrc.atlassian.net/browse/COR-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[COR-480]: https://dteam-nrc.atlassian.net/browse/COR-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> COR-480: add missing text styles

- frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.test.ts
- frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
I noticed some issues with the auth flow when developing core-app. This should fix things and make developing a bit easier. I still thing hot reloading isn't working as it should though.
* Token refresh was broken as we weren't actually passing through the refresh token
* Implement the session token cache that we had on the pwa for web only
> Auth fixes

- frontend/apps/core-app/src/components/RecordEditor/FieldInput/CheckboxFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/DateFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/MonthFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/MultiSelectFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/MultilineTextFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/QuantityFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/ReferenceFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/SingleSelectFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/SubFormFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/TextFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/WeekFieldInput.component.tsx
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/CheckboxFieldInput.component.test.tsx.snap
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/MultiSelectFieldInput.component.test.tsx.snap
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/MultilineTextFieldInput.component.test.tsx.snap
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/QuantityFieldInput.component.test.tsx.snap
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/SubFormFieldInput.component.test.tsx.snap
- frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/TextFieldInput.component.test.tsx.snap
- frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.component.tsx
- frontend/packages/core-api-client/src/client/Recipient.ts
- frontend/packages/core-api-client/src/client/__tests__/Recipient.test.ts
- frontend/packages/core-api-client/src/index.ts
- frontend/packages/core-api-client/src/validation/Recipient.ts
- frontend/packages/core-api-client/src/validation/Record.ts
- frontend/packages/core-api-client/src/validation/index.ts
Adds form validation and validates the recipient hierarchy when creating.
I want to look into using io-ts for validation (there's a plugin for rhf) but this will suffice for now.
> Cor 486 registration page validation

- frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
This fixes an issue where all tokens had expired and the UI wouldn't fallback to the login screen
> More auth fixes
